# Generated by Django 4.2 on 2024-07-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tag_color',
            field=models.CharField(choices=[('R', 'Red'), ('P', 'Pink'), ('C', 'Cyan')], default='R', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(choices=[('N', 'New'), ('F', 'Featured')], max_length=1),
        ),
    ]
