# Generated by Django 4.2 on 2024-07-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_tag_color_alter_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(choices=[('New', 'New'), ('Featured', 'Featured')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag_color',
            field=models.CharField(choices=[('Red', 'Red'), ('Pink', 'Pink'), ('Cyan', 'Cyan')], max_length=100),
        ),
    ]
