# Generated by Django 4.2 on 2024-07-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_tag_alter_item_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(choices=[('N', 'New'), ('F', 'Featured')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag_color',
            field=models.CharField(choices=[('R', 'Red'), ('P', 'Pink'), ('C', 'Cyan')], max_length=100),
        ),
    ]
